version: "3"
services:
  client:
    image: "smallies/dockerhub-struct:structure-client:v1.0.0"
    mem_limit: 128m
    hostname: client
    stdin_open: true
  server:
    image: "smallies/dockerhub-struct:structure-server:v1.0.0"
    mem_limit: 128m
    hostname: api
  #   environment:
  #     - REDIS_HOST=$REDIS_HOST
  #     - REDIS_PORT=$REDIS_PORT
  #     - PGUSER=$PGUSER
  #     - PGHOST=$PGHOST
  #     - PGDATABASE=$PGDATABASE
  #     - PGPASSWORD=$PGPASSWORD
  #     - PGPORT=$PGPORT
  # worker:
  #   image: "cygnetops/multi-worker-10-14"
  #   mem_limit: 128m
  #   hostname: worker
  #   environment:
  #     - REDIS_HOST=$REDIS_HOST
  #     - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "smallies/dockerhub-struct:structure-nginx:v1.0.0"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
